[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "remix watch"
  port = 8080

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
    start = "npx netlify dev"

  [plugins.inputs]
    enable = false