[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.preBuild]
    enable = true
    start = 'npx netlify dev'
    wait-on = 'http://localhost:8888'

  [plugins.inputs]
    enable = false